FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN python3 -m venv venv
ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

RUN ls -la /app

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8080", "app.app:app"]
